### ISSUE TITLE
Igor Pro compilation issue

### ISSUE THREAD

**Issue by bnash** [ochubar/SRW#25]
Hello Oleg,
I was recently contacted from someone having issues with compiling the Igor Pro interface to SRW, so I tried to run SRW on Igor Pro again myself.

I am running Igor Pro 7 on Mac OS Catalina, and I downloaded the latest version of the srw_igor folder.
When I start Igor Pro, the SRW compilation fails with a number of errors such as 
![Screen Shot 2020-07-13 at 10 55 29 AM](https://user-images.githubusercontent.com/1112276/87331951-0dc26a80-c4f8-11ea-80e2-f5522294410c.png)

Is there an easy fix to this problem?
Thanks,
Boaz

**Comment by ochubar** [comment]
Hello Boaz,

Our SRW repository contains compiled Igor (7/8) 64-bit extension for a recent version of macOS:
https://github.com/ochubar/SRW/tree/master/env/work/srw_igor/SRW/SRW_MAC64.xop
It may look like a folder on non-mac platform, but on macOS, it should look just like file "SRW_MAC64.xop". 
For the installation of this SRW version on macOS, see this ReadMe file:
https://github.com/ochubar/SRW/blob/master/env/work/srw_igor/SRW/ReadMe.txt
Note that your pasted error message probably means that it was not installed correctly. See in particular the NOTE in the ReadMe about walking around the security issues on macOS. We tried it with several colleagues - seems to work.

We also have Xcode project for re-compiling SRW for macOS:
https://github.com/ochubar/SRW/tree/master/cpp/xcode/SRWLClientIgor.xcodeproj

There may be also an issue that these mac files may appear compressed after you download them. Try to figure-out what may need to be uncompressed.
Hope this helps.

**Comment by bnash** [comment]
Thanks for the reply @ochubar. I will give this a try and pass this information on to the other person who asked for help in this issue.
